config/routes.rb
Rails.application.routes.draw do
  LOCALES = /en|pt\-BR/

  scope "(:locale)", locale: LOCALES do
    resources :rooms
    resources :users

    resource :confirmation, only: [:show]

    resource :user_sessions, only: [:create, :new, :destroy]
  end

  get '/:locale' => 'home#index', locales: LOCALES
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  scope :most_recent, -> {order('created_at DESC')}

  def complete_name
    "#{title}, #{location}"
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :rooms

    validates_presence_of :email, :full_name, :location
    validates_length_of :bio, minimum: 30, allow_blank: false
    validates_format_of :email, with: /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/
    validates_uniqueness_of :email

    scope :confirmed, -> { where('confirmed_at IS NOT NULL') }
    scope :most_recent, -> {order('created_at DESC')}

    has_secure_password

    before_create :generate_token

    def generate_token
        self.confirmation_token = SecureRandom.urlsafe_base64
    end

    def confirm!
        return if confirmed?

        self.confirmed_at = Time.current
        self.confirmation_token = ''
        save!
    end

    def confirmed?
        confirmed_at.present?
    end

    def self.authenticate(email, password)
      confirmed.find_by_email(email).try(:authenticate, password)
    end
end

app/models/user_session.rb
class UserSession
    include ActiveModel::Model

    attr_accessor :email, :password

    validates_presence_of :email, :password

    def initialize(session, attributes={})
        @session = session
        @email = attributes[:email]
        @password = attributes[:password]
    end

    def authenticate
        user = User.authenticate(@email, @password)

        if user.present?
            store(user)
        else
            errors.add(:base, :invalid_login)
            false
        end
    end

    def store(user)
        @session[:user_id] = user.id
    end

    def persisted?
        false
    end

    def current_user
      User.find(@session[:user_id])
    end

    def user_signed_in?
      @session[:user_id].present?
    end

    def destroy
      @session[:user_id] = nil
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery

    delegate :current_user, :user_signed_in?, to: :user_session
    helper_method :current_user, :user_signed_in?

    before_action :set_locale

    def set_locale
        I18n.locale = params[:locale] || I18n.default_locale
    end

    def default_url_options
        { locale: I18n.locale }
    end

    def user_session
      UserSession.new(session)
    end

    def require_authentication
      unless user_signed_in?
        redirect_to new_user_sessions_path, alert: t('flash.alert.needs_login')
      end
    end

    def require_no_authentication
      redirect_to root_path if user_signed_in?
    end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < ApplicationController
    def show
        user = User.find_by_confirmation_token(params[:token])

        if user.present?
            user.confirm!
            redirect_to user, notice: I18n.t('users.confirmations.success')
        else
            redirect_to root_path
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @rooms = Room.limit(3)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :require_authentication, only: [:new, :edit, :create, :update, :destroy]
  before_action :set_room, only: %i[ show edit update destroy ]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.most_recent
  end

  # GET /rooms/1 or /rooms/1.json
  def show
    @room = Room.find(params[:id])
  end

  # GET /rooms/new
  def new
    @room = current_user.rooms.build
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms or /rooms.json
  def create
    @room = current_user.rooms.build(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: t('flash.notice.room_created') }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: t('flash.notice.room_updated') }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: "Room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = current_user.rooms.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:title, :location, :description)
    end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :require_authentication, only: :destroy

    def new
        @session = UserSession.new(session)
    end

    def create
        @session = UserSession.new(session, params[:user_session])
        if @session.authenticate
            redirect_to root_path, notice: t('flash.notice.signed_in')
        else
            render :new
        end
    end

    def destroy
        user_session.destroy
        redirect_to root_path, notice: t('flash.notice.signed_out')
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_no_authentication, only: [:new, :create]
  before_action :can_change, only: [:edit, :update]

    def new
        @user = User.new
    end

    def show
        @user = User.find(params[:id])
    end

    def create
        @user = User.new(user_params)
        if @user.save
            SignupMailer.confirm_email(@user).deliver
            redirect_to @user, notice: 'Cadastro criado com sucesso'
        else
            render :new
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to @user, notice: 'Cadastro atualizado com sucesso'
        else
            render :edit
        end
    end

    private

    def user_params
        params.require(:user).permit(:full_name, :email, :password, :password_confirmation, :location, :bio)
    end

    def can_change
      unless user_signed_in? && current_user == user
        redirect_to user_path(params[:id])
      end
    end

    def user
      @user ||= User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def error_tag(model, attribute)
        if model.errors.has_key? attribute
            content_tag :div,
            model.errors[attribute].first,
            class: 'error_message'
        end
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def belongs_to_user(room)
    user_signed_in? && room.user == current_user
  end
end

app/views/home/index.html.erb
<h1>Quartos recém postados</h1>

<ul>
    <% @rooms.each do |room| %>
        <li><%= link_to room.complete_name, room %></li>
    <% end %>
</ul>

app/views/layouts/_user_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.new_room'), new_room_path %></li>
    <li><%= link_to t('layout.rooms'), rooms_path %></li>
    <li><%= link_to t('layout.my_profile'), user_path(current_user) %></li>
    <li><%= link_to t('layout.signout'), user_sessions_path, method: :delete %></li>
  </ul>
</nav>

app/views/layouts/_visitor_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to t('layout.rooms'), rooms_path %></li>
    <li><%= link_to t('layout.signup'), new_user_path %></li>
    <li><%= link_to t('layout.signin'), new_user_sessions_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Colchonet</title>
    <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div id="header-wrap">
        <h1><%= link_to "colcho.net", root_path %></h1>
        <% if user_signed_in? %>
          <%= render 'layouts/user_navbar' %>
        <% else %>
          <%= render 'layouts/visitor_navbar' %>
        <% end %>
      </div>
    </header>

    <div id='content'>
      <% if notice.present? %>
        <p id='notice'><%= notice %></p>
      <% end %>

      <% if alert.present? %>
        <p id='alert'><%= alert %></p>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/_room.html.erb
<article class="room">
  <h2><%= link_to room.title, room %></h2>
  <span class="created">
    <%= t '.owner_html',
        owner: room.user.full_name,
        when: l(room.created_at, format: :short) %>
  </span>
  <p>
    <span class="location">
      <%= link_to room.location,
          "https://maps.google.com/?q=#{room.location}",
          target: :blank %>
    </span>
  </p>
  <p><%= room.description %></p>
  <% if belongs_to_user(room) %>
    <ul>
      <li><%= link_to t('.edit'), edit_room_path(room) %></li>
      <li><%= link_to t('.destroy'), room_path(room),
              method: :delete,
              data: {confirm: t('dialogs.destroy')} %></li>
    </ul>
  <% end %>
</article>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to t('links.back'), @room %>

app/views/rooms/index.html.erb
<h1><%= t '.title' %></h1>

<%= render @rooms %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<%= render @room %>

app/views/user_sessions/new.html.erb
<h1><%= t '.title' %></h1>

<% if @session.errors.has_key? :base %>
    <div id="error_explanation">
        <%= @session.errors[:base].join(', ') %>
    </div>
<% end %>

<%= form_for @session do |f| %>
    <p>
        <%= f.label :email %>
        <%= f.text_field :email %>
        <%= error_tag @session, :email %>
    </p>

    <p>
        <%= f.label :password %>
        <%= f.password_field :password %>
        <%= error_tag @session, :password %>
    </p>

    <%= f.submit %>
<% end %>

<p><%= link_to t('.sign_up'), new_user_path %></p>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <%= t ('general.form_error') %>
    </div>
<% end %>

<%= form_for @user do |f| %>
    <p>
        <%= f.label :full_name %><br />
        <%= f.text_field :full_name %>
        <%= error_tag @user, :full_name %>
    </p>
    <p>
        <%= f.label :location %><br />
        <%= f.text_field :location %>
        <%= error_tag @user, :location %>
    </p>
    <p>
        <%= f.label :email %><br />
        <%= f.text_field :email %>
        <%= error_tag @user, :email %>
    </p>
    <p>
        <%= f.label :password %><br />
        <%= f.password_field :password %>
        <%= error_tag @user, :password %>
    </p>
    <p>
        <%= f.label :password_confirmation %><br />
        <%= f.password_field :password_confirmation %>
        <%= error_tag @user, :password_confirmation %>
    </p>
    <p>
        <%= f.label :bio %><br />
        <%= f.text_area :bio %>
        <%= error_tag @user, :bio %>
    </p>
    <%= f.submit %>
<% end %>

app/views/users/edit.html.erb
<h1><%= t '.title' %></h1>
<%= render 'form' %>
<%= link_to t('links.back'), @user %>

app/views/users/new.html.erb
<h1><%= t '.title' %></h1>
<%= render 'form' %>
<%= link_to t('links.back'), root_path %>

app/views/users/show.html.erb
<h2><%= t '.title', user_name: @user.full_name %></h2>

<ul>
    <li><%= t '.location', location: @user.location %></li>
    <li><%= t '.bio', bio: @user.bio %></li>
</ul>

<%= link_to t('.edit'), edit_user_path(@user) %>